### ISSUE TITLE
is there any way to have the go.mod create m3u files aswell? 

### ISSUE THREAD

**Issue by bitsbb01** [wudongdefeng/IPTVCAT#1]
is it possible to have it create also .m3u files? 
eg. for the countries, have it also create a .m3u file for each country making them able to be used for iptv. without having to convert them manually by each channel. 

Thanks in advance

**Comment by wudongdefeng** [comment]
I use it to filtering  channels in Hikerview software. And I use the tv mirroring to see the channels.You can try it.[expample](https://s1.ax1x.com/2020/11/11/BX5gCd.jpg)
https://www.lanzous.com/u/GoldRiver
