### ISSUE TITLE
You Can Contributed To Freearhey's IPTV?

### ISSUE THREAD

**Issue by cheznewa** [wudongdefeng/IPTVCAT#3]
hello, your repo is very greate, a very large choose of channels but with duplicateds, but is very good if you contributed from ::::::::::::::::::: https://github.com/iptv-org/iptv ?

an advice, in this repo (iptv-org/iptv) contribute in m3u and do not duplicate.

please/thank you.

Newa Our Master/Newa Notre Maitre.

**Comment by wudongdefeng** [comment]
Thanks for your invitation,I've a project to duplicated m3u files to txt.You can see it in github.com/wudongdefeng/iptv-tools,maybe it's useful for you team
